apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  index.html: |
    <html>
      <head>Page</head>
      <body>
        <h1>The last work is completed successfully</h1>
      </body>
    </html>
