apiVersion: apps/v1
kind: Deployment
metadata: 
  name: html-page-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: html-page
  template: 
    metadata:
      labels:
        app: html-page
    spec: 
      containers:
      - name: nginx
        image: nginx:1.26.2
        ports:
        - containerPort: 80
        volumeMounts: 
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap: 
          name: html-page-config